language: python
python: '3.5'
env:
  matrix:
    - TOXENV=py27 CLANG=3.5
    - TOXENV=py34 CLANG=3.5
    - TOXENV=py35 CLANG=3.5
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - tox -v
cache: pip
