language: python
python: '3.5'
sudo: false
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=noclang
    - CXX=g++-6
    - CXX=clang++-3.8
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - virtualenv --version
  - pip --version
  - if [ $TOXENV ]; then pip install tox; fi
  - if [ $TOXENV ]; then tox --version; fi
  - if [ $CXX ]; then $CXX --version; fi
  - if [ $CXX ]; then pip install .; fi
  - if [ $CXX ]; then mkdir -p /tmp/gtest && cd /tmp/gtest && cmake /usr/src/gtest && make && export LIBRARY_PATH=${LIBRARY_PATH}:/tmp/gtest && cd -; fi
script:
  - if [ $TOXENV ]; then tox -v; fi
  - if [ $CXX ]; then cd prophy_cpp && ./waf configure test dist -j1; fi
cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8
      - libgtest-dev
      - valgrind
