language: python
python: '3.5'
sudo: false
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - CXX=g++-6
    - CXX=clang++-3.8
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - virtualenv --version
  - pip --version
  - if [ $TOXENV ]; then pip install tox; tox --version; fi
  - if [ $CXX ]; then $CXX --version; fi
script:
  - if [ $TOXENV ]; then tox -v; fi
  - if [ $CXX ]; then cd prophy_cpp; ./waf configure test dist; fi
cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - gcc-6
      - g++-6
      - clang-3.8
